version: '3.1'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_USER: api
      MYSQL_ROOT_PASSWORD: password
      MYSQL_PASSOWORD: password
      MYSQL_DATABASE: termineDB
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306